### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by tomgross**
Add buildout, remove unneeded test dependency and fix test assertions for Python 3

### CODE REVIEW

**Comment by gforcada** [comment]
@tomgross I hope you would not mind that I added another commit on your branch to fix the tests on 2.7.

I haven't tried it on 2.6 (although you explicitly removed it on setup.py trove classifiers), but as long as we don't change it, master is still supposed to be compatible with Plone 4.3 and this means python 2.6 support.

IMHO, adding support for python 3.x is a reason good enough to create a maintenance branch for Plone 4.3 and keep master only for Plone 5.x

**Comment by tomgross** [comment]
@gforcada Thanks for the review and the fix. I'm not sure if `unicode_literals` are available for Python 2.6 so I removed it from the trove classifiers. I conform on having a new branch for Python 3 and 2.7.

**Comment by jensens** [comment]
ok, its a good idea to branch waway for Plone 4.3

**Comment by gforcada** [comment]
@tomgross @jensens I created a 4.1 just before this pull request and updated buildout.coredev 4.3 branch to point to that branch on sources.cfg

**Comment by gforcada** [comment]
Lastly, I added it to https://github.com/plone/buildout.coredev/blob/5.1/experimental/py3x-test.cfg so the tests run on http://jenkins.plone.org/view/py3/job/py3-test/

**Pull request merged**
